INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'RHEL');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'SAT');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OSP');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'CTOS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'JBAP');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'JBWS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'DGR');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OAR');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'CRS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'CRW');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'QARK');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'FUSE');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'FUSO');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'AMQ');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'3SAM');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'DMNG');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'PAM');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'RHEV');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'HYIF');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OSP');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OCP');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'CSYS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OAR');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'DSRV');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'ODF');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'HYIF');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'QUAY');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OSSM');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'OSLS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'ODS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'GLS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'CEPH');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'HYIF');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'ODF');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'SMGM');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'SAT');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'AAP');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'INSG');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'ACM');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'SEC');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'ACS');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'AIML');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'RHOIC');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'SCAP');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'TCAL');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'SAPDI');
INSERT INTO public.product("id", "name") VALUES(nextval('hibernate_sequence'),'RHPDS');

INSERT INTO public.level("id", "description", "level") VALUES(1,'L100','Basic');
INSERT INTO public.level("id", "description", "level") VALUES(2,'L200','Advanced');
INSERT INTO public.level("id", "description", "level") VALUES(3,'L300','Experienced');

INSERT INTO public.stage("id", "title") VALUES(1,'Analysis');
INSERT INTO public.stage("id", "title") VALUES(2,'Test');
INSERT INTO public.stage("id", "title") VALUES(3,'QA');
INSERT INTO public.stage("id", "title") VALUES(4,'Production');

INSERT INTO public.asset("id", "type") VALUES(1,'Wksp');
INSERT INTO public.asset("id", "type") VALUES(2,'Demo');
INSERT INTO public.asset("id", "type") VALUES(3,'Lab');